# Generated by Django 3.1.3 on 2021-09-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('order_name', models.ManyToManyField(to='mypp.order')),
            ],
        ),
    ]
